package com.palm360.airport.model;

import java.io.Serializable;

import com.palm360.airport.util.stereotype.DBIndexKey;
import com.palm360.airport.util.stereotype.ForeignKey;
import com.palm360.airport.util.stereotype.NoCache;
import com.palm360.airport.util.stereotype.PrimaryKey;
import com.palm360.airport.util.stereotype.SortedSet;

public class County extends BaseModel implements Serializable{
    
	@NoCache
	private static final long serialVersionUID = 5542966088795993728L;

	@PrimaryKey
    private Integer countyid;

    @ForeignKey
    private Integer cityid;

    @DBIndexKey
    private String countyname;
    @SortedSet
    private Float llongitude;
    @SortedSet
    private Float llatitude;
    @SortedSet
    private Float rlongitude;
    @SortedSet
    private Float rlatitude;
    
    private String longkey;

    private String sortkey;

    public Integer getCountyid() {
        return countyid;
    }

    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    public Integer getCityid() {
        return cityid;
    }

    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public String getCountyname() {
        return countyname;
    }

    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    public Float getLlongitude() {
        return llongitude;
    }

    public void setLlongitude(Float llongitude) {
        this.llongitude = llongitude;
    }

    public Float getLlatitude() {
        return llatitude;
    }

    public void setLlatitude(Float llatitude) {
        this.llatitude = llatitude;
    }

    public Float getRlongitude() {
        return rlongitude;
    }

    public void setRlongitude(Float rlongitude) {
        this.rlongitude = rlongitude;
    }

    public Float getRlatitude() {
        return rlatitude;
    }

    public void setRlatitude(Float rlatitude) {
        this.rlatitude = rlatitude;
    }

    public String getLongkey() {
        return longkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column County.LongKey
     *
     * @param longkey the value for County.LongKey
     *
     * @abatorgenerated Fri May 18 11:00:01 CST 2012
     */
    public void setLongkey(String longkey) {
        this.longkey = longkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column County.SortKey
     *
     * @return the value of County.SortKey
     *
     * @abatorgenerated Fri May 18 11:00:01 CST 2012
     */
    public String getSortkey() {
        return sortkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column County.SortKey
     *
     * @param sortkey the value for County.SortKey
     *
     * @abatorgenerated Fri May 18 11:00:01 CST 2012
     */
    public void setSortkey(String sortkey) {
        this.sortkey = sortkey;
    }
}
